# Generated by Django 4.2.13 on 2024-06-04 07:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_note_category_note_text_alter_note_deadline'),
    ]

    operations = [
        migrations.CreateModel(
            name='Done',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='done_done', to='core.note')),
                ('user', models.ManyToManyField(related_name='done_done', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
