# Generated by Django 4.2.13 on 2024-06-06 17:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0004_note_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='status',
            field=models.BooleanField(null=True, verbose_name='статус задачи'),
        ),
        migrations.AlterField(
            model_name='done',
            name='note',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='done', to='core.note'),
        ),
        migrations.AlterField(
            model_name='done',
            name='user',
            field=models.ManyToManyField(related_name='done', to=settings.AUTH_USER_MODEL),
        ),
    ]
